"""`(1,21)` NPC-BUY: the request, the ack and the frames that answer it.

Measured 2026-09-27 from the live reference's own four buys
(`DFO110-0.3.6/Server/Logs/server-20260927.log`, conn=2, account 0,
character 2)::

    22:54:05  shop=30 item=29127  gold 45500          ack 192B, 3 frames
    23:15:29  shop=15 item=3034   5 x material 3037   ack 200B, 4 frames
    23:15:30  shop=15 item=3035   5 x material 3037   ack 200B, 4 frames
    23:15:31  shop=15 item=1106   gold 100            ack 192B, 3 frames

The request is 24B: `u32le item | u32le count | u32le shop | u32le field | 8
zeros`.  `shop` and `field` are the reference's own words, and the field is
the shop rule's npc on all four (30->57, 15->2).  The second word is the
count: 1 on the three stackable buys here, and the reference's own log lines
read `count=184`, `466`, `389`, `450` on bulk buys of stackables in other
shops.  The 29127 equipment buy sent 46115 there and the reference still
logged `count=1` and spent 45500 once -- so a stackable buys `word` units,
anything else one (`BuyRequest.count`).

The ack is 187B of content padded to 8::

    u8 01 | u32le gold-after | 16 zero bytes | 165B bought-row block |
    u8 n_paid | n x 12B (u32le item, u32le count-after, u32le bag cell)

192B with nothing paid in materials, 200B with one (measured; the 29127
frame carries `01 92 06 00 00` then its slot-17 row, the 3034 frame `01 6a
bc 00 00` then slot 364 and `01` + 3037's 12B).  `gold-after` moves on all
four, including the two zero-gold buys, whose gold row goes out in the
character frame with its count unchanged (48234).

Three or four frames follow, each a `(0,14)` body out of `refresh`::

    (1,21)   ack
    (0,14)   the *character* frame: the gold row (slot 0), plus the bought
             row when it landed in `character_items`
    (0,14)   the *material* frame: the paid materials in cost order, plus
             the bought row when it landed in `account_materials`
    (0,1361) 16B `32` + 15 zeros

so the 29127 and 1106 runs send 2 + 1 records (336B char frame, no material
frame) and the 3034/3035 runs 1 + 2 (168B char frame, 336B material frame,
paid 3037 first at cell 367 then the bought 3034 at 364).

**Where the item lands** is two rules, both read off the save.  A shop rule
whose `path` starts `stackable/material/` lands in `account_materials`,
addressed by *cell* out of the band table (`BAG_ITEMS`: 3034 -> 364,
3035 -> 365, both measured, and the paid 3037 sits at its band cell 367
already); anything else lands in `character_items` list 0, in the
first free slot of its catalogue `kind`'s range -- 65 for the stackable
1106, 17 for the equipment 29127.  The 17 is a *scan* anchor, not just a
number: the character sold the rows at list-0 slots 9..15 and 17 at
23:15:16 (`NPC-SELL-22`, 29127 from slot 17) and nothing between the buy and
the sell touched those slots, so at 22:54:05 cells 9..16 were occupied and 17
was the first free cell at or past the equipment base.  A bought equipment
row is born with a
fresh random `instance_value` (under 2^31: 700543244 was the 29127 one) and
its catalogue durability (48, the value the captured row block carries at
`[11]`), a stackable with 0 and count 1.

The two cell bases (equipment from 9, stackables from 65) are the module's
inferred parts, and so are the edges no capture
shows: a bought stack merging into a row the character already has (both
ends do -- `account_materials` has no slot to insert at), every refusal --
not in that shop, no gold, not enough materials, no free cell, a body that
is not 24B (the reference's own `rejected=malformed request error=250`) --
which writes nothing and answers nothing, like the other write paths', and a
multi-unit
buy: the reference's log shows it commits `count=184` buys, but no capture
has hex for one, so what such a buy pays and moves -- the gold and every
material times its units -- and the ack and the two `(0,14)` frames it sends
are generated by the measured grammar and unverified.

What is *not* inferred: the four runs above, byte for byte, against a copy
of the save -- `tests/test_buy_npc.py`.
"""
from __future__ import annotations

import random
import sqlite3
import struct
import time
from dataclasses import dataclass, replace

from ...persistence import items, materials
from ...protocol import frame
from ..data import content, load
from ..item import refresh

OPCODE = frame.Opcode(1, 21, frame.OpcodeEncoding.U8_U16LE, True)
BODY_SIZE = 24

GOLD_LIST = 0
GOLD_SLOT = 0

#: `account_materials` has no slot column.  The bag is a fixed band of twelve
#: cells -- this one first -- in this exact order, pinned on 44 `TOWN-ITEMS`
#: lines over the seven reference logs (09-19..09-30): every line carries
#: exactly these ids at these cells, counts moving and cells never, and the
#: 09-19 band is all twelve at count=0, so the band is a table the account's
#: counts fill, not a list its rows generate.  The order is not item-id order
#: -- 10100115/10100116 sit above the 10099773-10099775 trio -- and no
#: catalogue or save column sorts into it (brute-forced 09-30), so it is a
#: constant.  `game.town.burst.Inventory` is the band's other reader.
BAG_CELL_BASE = 363
BAG_ITEMS = (3033, 3034, 3035, 3036, 3037, 3262, 10100115, 10100116,
             10099773, 10099774, 10099775, 10158124)
#: The first cell an item *off* the band takes.  Nothing off the twelve ever
#: entered a bag anywhere in the logs, so the rest of the bag's numbering is
#: unobserved; an off-band material lines up behind the band in item-id order
#: -- inferred.
BAG_AFTER = BAG_CELL_BASE + len(BAG_ITEMS)
#: What a `stackable/material/` shop rule's path means.
MATERIAL_PREFIX = "stackable/material/"
#: The first list-0 cell a bought item may take, by catalogue `kind`:
#: equipment (0) from 9, stackables (1) from 65.  Both are where their buy
#: landed with cells free below the base -- 1106 skipped every one under 65,
#: 29127 the eight under 9.  How far a kind's run *ends* is not read here:
#: the scan runs to the last character cell, `BAG_CELL_BASE` - 1.
BAG_BASES = {0: 9, 1: 65}
#: Items that take a cell below their kind's base.  Item 1 -- the revive coin
#: the cera shop sells -- is the only one measured: six buys over three days
#: and both characters landed it at cell 1 (`game.shop.cera` has the runs),
#: each on a character whose cell 1 was free, so 1 is a *reading* of where its
#: band starts and not a rule that was read out of the catalogue (its kind,
#: type_index, rarity, grade and attach_index all fail to single it out).
#: The band still ends at the equipment base -- that the coin may take cells
#: 1..8 and nothing reads above 9 is the one bound the captures leave open.
SLOT_BASE_OVERRIDES = {1: 1}
#: A fresh equipment row's `instance_value` is a nonzero u31; the reference's
#: own values are all in that band, and nothing shows the draw.
INSTANCE_LIMIT = 1 << 31

TAG = "NPC-BUY-21"


@dataclass(frozen=True, slots=True)
class BuyRequest:
    """One `(1,21)` body: the item, the units, the shop and its npc."""

    item_id: int
    word: int
    shop_id: int
    field: int

    @classmethod
    def parse(cls, plain: bytes) -> "BuyRequest":
        if len(plain) != BODY_SIZE:
            raise ValueError(f"(1,21) body is {len(plain)}B, expected {BODY_SIZE}")
        item_id, word, shop_id, field = struct.unpack_from("<IIII", plain, 0)
        return cls(item_id=item_id, word=word, shop_id=shop_id, field=field)

    @property
    def count(self) -> int:
        """The units this buy asks for -- see the module docstring.

        The catalogue's `kind` decides: an equipment item (kind 0) buys one
        however big the word is, everything else buys the word.  A zero word
        buys one too; no capture shows one, so it is a floor, not a reading.
        """
        definition = content.definition(self.item_id)
        if definition is not None and definition.kind == 0:
            return 1
        return max(1, self.word)

    def request_line(self, conn: int) -> str:
        return (f"conn={conn} request shop={self.shop_id} item={self.item_id} "
                f"count={self.count} field={self.field} layout=npc mode=0")


@dataclass(frozen=True, slots=True)
class MaterialMove:
    """One paid material, as the ack and the material frame carry it."""

    item_id: int
    count: int                  # count after payment
    cell: int


@dataclass(frozen=True, slots=True)
class Outcome:
    ok: bool
    price: int = 0
    material_slots: int = 0
    gold_after: int = 0
    bought: refresh.SlotRecord | None = None
    paid: tuple[MaterialMove, ...] = ()
    char_records: tuple[refresh.SlotRecord, ...] = ()
    material_records: tuple[refresh.SlotRecord, ...] = ()
    #: Why nothing was written, for the caller's WARN.
    reason: str = ""


def shop_rule(item_id: int) -> dict | None:
    """The `npc_shop_rules` entry for an item: its price, cost and path."""
    rules = load("npc_shop_rules")
    return rules["items"].get(str(item_id))


def in_shop(shop_id: int, item_id: int) -> bool:
    shop = load("npc_shop_rules")["shops"].get(str(shop_id))
    return shop is not None and item_id in shop["items"]


def into_bag(rule: dict) -> bool:
    """Whether this rule's item lands in `account_materials`."""
    return rule["path"].startswith(MATERIAL_PREFIX)


def bag_cell(conn: sqlite3.Connection, account_id: int, item_id: int) -> int:
    """The cell the client shows an `account_materials` row in.

    On the band it is the fixed table's own address (3034 -> 364,
    3035 -> 365 and the paid 3037 at 367, all measured on the 09-27 buys);
    off it, the row lines up behind the band in item-id order -- inferred,
    no capture shows an off-band item in a bag either way.
    """
    if item_id in BAG_ITEMS:
        return BAG_CELL_BASE + BAG_ITEMS.index(item_id)
    rank = conn.execute(
        "select count(*) from account_materials where account_id = ? "
        f"and item_id < ? and item_id not in "
        f"({', '.join('?' * len(BAG_ITEMS))})",
        (account_id, item_id, *BAG_ITEMS)).fetchone()[0]
    return BAG_AFTER + rank


def base_for(item_id: int) -> int:
    """The first list-0 cell this item's band starts at -- see `BAG_BASES`
    and `SLOT_BASE_OVERRIDES`."""
    if item_id in SLOT_BASE_OVERRIDES:
        return SLOT_BASE_OVERRIDES[item_id]
    definition = content.definition(item_id)
    kind = definition.kind if definition is not None else 1
    return BAG_BASES.get(kind, BAG_BASES[1])


def free_slot(conn: sqlite3.Connection, character_id: int, item_id: int
              ) -> int | None:
    """The slot a bought item goes to: where a row of the same item already
    sits, else the first free cell at or past its band's base.  A stack already
    in the bag takes the buy -- inferred, no capture merges.
    """
    rows = conn.execute(
        "select slot_index, item_id from character_items where character_id = ? "
        "and list_type = ? order by slot_index",
        (character_id, GOLD_LIST)).fetchall()
    taken = {row[0] for row in rows}
    for slot, held in rows:
        if held == item_id and slot != GOLD_SLOT:
            return slot
    for slot in range(base_for(item_id), BAG_CELL_BASE):
        if slot not in taken:
            return slot
    return None


def fresh_row(character_id: int, slot: int, item_id: int, count: int,
              now: int) -> items.ItemStack:
    """A bought row: the catalogue's durability, a fresh u31 `instance_value`
    for equipment and nothing else carried over."""
    definition = content.definition(item_id)
    kind = definition.kind if definition is not None else 1
    return items.ItemStack(
        character_id=character_id, list_type=GOLD_LIST, slot_index=slot,
        item_id=item_id, count=count,
        durability=definition.durability if definition is not None else 0,
        instance_value=(random.randrange(1, INSTANCE_LIMIT) if kind == 0 else 0),
        random_options=b"", avatar_sockets=b"", clone_appearance_id=0,
        reinforcement=0, refinement=0, fusion_item="", bakal_state="",
        transferred_option_mask=0, enchant_card_id=0, enchant_upgrade=0,
        mist_imbued=0, updated_at=now, expires_at=0, custom_option_ids=0,
        growth_experience=0, amplify_type=0, amplify_value=0)


def execute(conn: sqlite3.Connection, account_id: int, character_id: int,
            request: BuyRequest, *, now: int | None = None) -> Outcome:
    """Charge the gold and materials, land the item, commit -- one transaction.

    Every check runs before the first write, so a refusal leaves the save as
    it was.  The records the outcome carries are read back from the rows, the
    way the `(0,14)` frames' own docstring (in `refresh`) says the reference
    sends them.
    """
    now = int(time.time()) if now is None else now
    with conn:
        rule = shop_rule(request.item_id)
        if rule is None:
            return Outcome(False, reason="item is not in any shop")
        if not in_shop(request.shop_id, request.item_id):
            return Outcome(False, reason="item is not in that shop")
        gold = items.load(conn, character_id, GOLD_LIST, GOLD_SLOT)
        if gold is None:
            return Outcome(False, reason="no gold row")
        count = request.count
        price = int(rule["gold"]) * count
        if gold.count < price:
            return Outcome(False, reason="not enough gold")
        cost = [(int(entry["item"]), int(entry["count"]) * count)
                for entry in rule["materials"]]
        for item_id, need in cost:
            row = materials.load(conn, account_id, item_id)
            if row is None or row.count < need:
                return Outcome(False, reason="not enough materials")
        bag = into_bag(rule)
        slot = None
        if not bag:
            slot = free_slot(conn, character_id, request.item_id)
            if slot is None:
                return Outcome(False, reason="no free slot")

        items.set_count(conn, gold, gold.count - price, now)
        for item_id, need in cost:
            row = materials.load(conn, account_id, item_id)
            materials.set_count(conn, account_id, item_id, row.count - need, now)

        bought = _land(conn, account_id, character_id, request, count, bag, slot,
                       now)

        gold_row = items.load(conn, character_id, GOLD_LIST, GOLD_SLOT)
        char_records = [refresh.SlotRecord.of_stack(gold_row, GOLD_SLOT)]
        paid = []
        material_records = []
        for item_id, _need in cost:
            row = materials.load(conn, account_id, item_id)
            cell = bag_cell(conn, account_id, item_id)
            paid.append(MaterialMove(item_id, row.count, cell))
            material_records.append(refresh.SlotRecord(
                slot_index=cell, item_id=item_id, value=row.count))
        if bag:
            material_records.append(bought)
        else:
            char_records.append(bought)
    return Outcome(True, price=price, material_slots=len(cost),
                   gold_after=gold.count - price, bought=bought,
                   paid=tuple(paid), char_records=tuple(char_records),
                   material_records=tuple(material_records))


def _land(conn: sqlite3.Connection, account_id: int, character_id: int,
          request: BuyRequest, count: int, bag: bool, slot: int | None, now: int
          ) -> refresh.SlotRecord:
    """Write the bought row and return the record the ack and frames carry.

    `count` is the units bought: a row already there moves up by as many, a
    fresh one is born with them.
    """
    if bag:
        existing = materials.load(conn, account_id, request.item_id)
        held = count if existing is None else existing.count + count
        if existing is None:
            materials.insert(conn, account_id, request.item_id, held, now)
        else:
            materials.set_count(conn, account_id, request.item_id, held, now)
        cell = bag_cell(conn, account_id, request.item_id)
        return refresh.SlotRecord(slot_index=cell, item_id=request.item_id,
                                  value=held)
    existing = items.load(conn, character_id, GOLD_LIST, slot)
    if existing is not None:
        held = existing.count + count
        items.set_count(conn, existing, held, now)
        row = replace(existing, count=held, updated_at=now)
    else:
        row = fresh_row(character_id, slot, request.item_id, count, now)
        items.insert(conn, row)
    return refresh.SlotRecord.of_stack(row)


def ack(outcome: Outcome) -> bytes:
    """The 187B content: `01`, the gold after, 16 zeros, the bought block,
    then the paid materials -- zero-padded to a multiple of 8."""
    out = bytearray(b"\x01")
    out += struct.pack("<I", outcome.gold_after)
    out += bytes(16)
    out += outcome.bought.block()
    out += bytes([len(outcome.paid)])
    for move in outcome.paid:
        out += struct.pack("<III", move.item_id, move.count, move.cell)
    return bytes(out) + bytes(-len(out) % 8)


def frames(outcome: Outcome) -> list[tuple[frame.Opcode, bytes]]:
    """The three or four frames, in the reference's order."""
    out = [(OPCODE, ack(outcome))]
    if outcome.char_records:
        out.append((refresh.OPCODE_SLOT,
                    refresh.slot_frame(GOLD_LIST, outcome.char_records)))
    if outcome.material_records:
        out.append((refresh.OPCODE_SLOT,
                    refresh.slot_frame(GOLD_LIST, outcome.material_records)))
    out.append((refresh.OPCODE_BOARD, refresh.BOARD_AFTER_WRITE_BODY))
    return out


def outcome_line(conn: int, request: BuyRequest, outcome: Outcome) -> str:
    return (f"conn={conn} shop={request.shop_id} item={request.item_id} "
            f"count={request.count} gold={outcome.price} "
            f"materialSlots={outcome.material_slots} limits=0 committed=true")
