"""`(1,22)` NPC-SELL: the request, the ack and the frames that answer it.

One sample exists in every log the project holds -- the live reference's own
sale at 09-27 23:15:16 (`DFO110-0.3.6/Server/Logs/server-20260927.log`,
conn=2, account 0, character 2), eight rows of list 0 sold at the weapon
shop's repair machine (npc 319, shop 96)::

    23:15:16.055  npc=319 shop=96 (weapon shop) rows=8 tail=20:
                  list 0 slot 9 ×1, 10 ×1, 11 ×1, 12 ×1, 13 ×1, 14 ×1,
                  15 ×1, 17 ×1
    23:15:16.063  sold item 13264 ×1 from list 0 slot 9 for 3744 gold
                  (3744 each), 0 left; ...; 48234 gold;
                  answered with the ack + (0,14)×1

Three frames answer it, 1624B: the 72B ack, one 1488B `(0,14)` (the gold row
plus the eight now-empty cells) and the 16B `(0,1361)` board constant.

The request is 104B::

    u32le npc | u32le shop | u16le rows
      | rows × 11B: u16le slot | u32le count | u32le cell | u8 00
      | 6 × 00

-- the eight rows of the one sample are list 0 slots 9..15 and 17, `count` 1
each, and `cell` reads `2 * slot + 2` on every one of them (20, 22, ..., 36,
skipping 34 with slot 16).  Slot 16 held item 22053 and the *client* left it
out of the request; nothing in the save distinguishes it but a catalogue
durability of 0, so the filter is the client's and nothing here re-imposes
it.  The address this module sells is the u16 `slot`; `cell` is carried only
for the request line's `tail` (below).

The ack, 66B of content padded to 72::

    u8 01 | u32le gold-after | u16le rows | 3 × 00
      | rows × 7B: u16le slot | u32le count-after | u8 00 | zero-pad to 8

**The price is the catalogue `value` over five** -- exact on all eight rows
(13264 `value`=18720 -> 3744, 100170173 -> 5488, 100220166 -> 4704,
100270170 -> 5184, 117020057 -> 6336, 100310851 -> 7776, 100320655 -> 6768,
29127 -> 6552).  The row's own `count` is the units sold; the sample sells 1
of 1 on every row, so `count-after` is 0 and each `(0,14)` block carries
`FF FF FF FF` -- a partial sale, a stack of 10 sold 3, is generated by the
same grammar and unverified.

**The request line's `tail` is a one-sample reading, not a rule.**  Its 20 on
the sample is row 0's `cell` (2 × 9 + 2) and nothing else in the body is 20 --
the six trailer bytes are zero -- so this module prints the first row's
`cell` there.  What the reference reads for the name is not derivable from a
single sale; see protocol.md.  The line ends with the body's own full
`plain=` dump (208 upper-case hex chars; the reference's `UNHANDLED` notes
stop at 96 bytes, request lines do not).

Every refusal -- an unknown shop, a repeated or empty slot, a non-positive
count, a count past what the row holds, slot 0 (the gold row the proceeds
are paid into, which cannot also be the thing sold), an item the catalogue
does not carry -- writes nothing and answers nothing, like the other write
paths'.  The gold row is refused by name because item 0 *is* in the
catalogue, as a zero-value placeholder, so the lookup would let it through.
No capture shows a refusal, so which of them the reference rejects silently
is inferred from the plain text of the rules.  Two rules the reference may
have that this module does not, both without evidence either way: the shop
entry's `blocked` list (non-empty on 100 of the 1057 shops) and the
client's own skip of the durability-0 item.

What is *not* inferred: the 23:15:16 sale byte for byte against a copy of the
save -- `tests/test_sell_npc.py`.
"""
from __future__ import annotations

import sqlite3
import struct
import time
from dataclasses import dataclass, replace

from ...persistence import items
from ...protocol import frame
from ..data import content, load
from ..item import refresh
from . import buy

OPCODE = frame.Opcode(1, 22, frame.OpcodeEncoding.U8_U16LE, True)

BODY_SIZE = 104
MAX_ROWS = 8
ROW_SIZE = 11
TRAILER_SIZE = 6

#: The per-unit price is the catalogue `value` over this -- exact over the
#: eight measured rows.
VALUE_DIVISOR = 5

TAG = "NPC-SELL-22"

GOLD_LIST = buy.GOLD_LIST
GOLD_SLOT = buy.GOLD_SLOT


@dataclass(frozen=True, slots=True)
class Row:
    """One requested sale line.  `cell` is the client's own `2 * slot + 2`."""

    slot: int
    count: int
    cell: int


@dataclass(frozen=True, slots=True)
class SellRequest:
    """One `(1,22)` body: the npc, its shop and the rows to sell."""

    npc: int
    shop: int
    rows: tuple[Row, ...]

    @classmethod
    def parse(cls, plain: bytes) -> "SellRequest":
        if len(plain) != BODY_SIZE:
            raise ValueError(f"(1,22) body is {len(plain)}B, "
                             f"expected {BODY_SIZE}")
        npc, shop, count = struct.unpack_from("<IIH", plain, 0)
        if count > MAX_ROWS:
            raise ValueError(f"(1,22) asks for {count} rows, "
                             f"more than {MAX_ROWS}")
        rows = []
        for i in range(count):
            slot, units, cell = struct.unpack_from(
                "<HII", plain, 10 + i * ROW_SIZE)
            rows.append(Row(slot=slot, count=units, cell=cell))
        return cls(npc=npc, shop=shop, rows=tuple(rows))

    @property
    def tail(self) -> int:
        """The request line's `tail` -- the first row's `cell`, a reading of
        the one sample (see the module docstring)."""
        return self.rows[0].cell if self.rows else 0

    def request_line(self, conn: int, shop_type: str, plain: bytes) -> str:
        """The reference's own line, `plain=` trailer and all -- upper case
        like the other request lines', and the whole 104B rather than the
        `UNHANDLED` notes' 96-byte cap."""
        sold = ", ".join(f"list 0 slot {row.slot} ×{row.count}"
                         for row in self.rows)
        return (f"conn={conn} npc={self.npc} shop={self.shop} ({shop_type}) "
                f"rows={len(self.rows)} tail={self.tail}: {sold} "
                f"plain={plain.hex().upper()}")


@dataclass(frozen=True, slots=True)
class Sale:
    """One row's sale, for the outcome line."""

    slot: int
    item_id: int
    count: int                  # units sold
    price: int                  # total for the row
    each: int
    left: int                   # count after


@dataclass(frozen=True, slots=True)
class Outcome:
    ok: bool
    gold_after: int = 0
    sales: tuple[Sale, ...] = ()
    #: The `(0,14)` records: the gold row, then every sold cell, in the
    #: request's order.
    records: tuple[refresh.SlotRecord, ...] = ()
    #: Why nothing was written, for the caller's WARN.
    reason: str = ""


def shop(item_id: int) -> dict | None:
    """The `npc_shop_rules` entry for a shop id."""
    return load("npc_shop_rules")["shops"].get(str(item_id))


def shop_type(shop_id: int) -> str:
    """The shop's own word for itself -- `weapon shop` on the one sample's."""
    entry = shop(shop_id)
    return "" if entry is None else entry["type"]


def execute(conn: sqlite3.Connection, account_id: int, character_id: int,
            request: SellRequest, *, now: int | None = None) -> Outcome:
    """Take the rows out of list 0, pay the gold, commit.

    Every check runs before the first write, so a refusal leaves the save as
    it was.  The gold lands in the slot-0 row, the same row the buys spend
    from, and the records are read back from what the rows now hold.
    """
    now = int(time.time()) if now is None else now
    with conn:
        if shop(request.shop) is None:
            return Outcome(False, reason="shop is not in the catalogue")
        if not request.rows:
            return Outcome(False, reason="no rows")
        gold = items.load(conn, character_id, GOLD_LIST, GOLD_SLOT)
        if gold is None:
            return Outcome(False, reason="no gold row")
        seen = set()
        planned = []
        total = 0
        for row in request.rows:
            if row.slot in seen:
                return Outcome(False, reason=f"slot {row.slot} is repeated")
            seen.add(row.slot)
            if row.count < 1:
                return Outcome(False, reason="a row's count is not positive")
            if row.slot == GOLD_SLOT:
                return Outcome(False, reason="slot 0 is the gold row")
            stack = items.load(conn, character_id, GOLD_LIST, row.slot)
            if stack is None:
                return Outcome(False, reason=f"slot {row.slot} is empty")
            definition = content.definition(stack.item_id)
            if definition is None:
                return Outcome(False, reason=f"item {stack.item_id} is not in "
                                             f"the catalogue")
            if row.count > stack.count:
                return Outcome(False, reason=f"slot {row.slot} holds "
                                             f"{stack.count} of {row.count}")
            each = definition.value // VALUE_DIVISOR
            planned.append((row, stack, each))
            total += each * row.count

        items.set_count(conn, gold, gold.count + total, now)
        sales = []
        cells = []
        for row, stack, each in planned:
            left = stack.count - row.count
            if left:
                items.set_count(conn, stack, left, now)
                cells.append(refresh.SlotRecord.of_stack(
                    replace(stack, count=left), row.slot))
            else:
                items.delete(conn, character_id, GOLD_LIST, row.slot)
                cells.append(refresh.SlotRecord.of_stack(None, row.slot))
            sales.append(Sale(slot=row.slot, item_id=stack.item_id,
                              count=row.count, price=each * row.count,
                              each=each, left=left))
        gold_row = items.load(conn, character_id, GOLD_LIST, GOLD_SLOT)
    return Outcome(True, gold_after=gold.count + total, sales=tuple(sales),
                   records=(refresh.SlotRecord.of_stack(gold_row, GOLD_SLOT),
                            *cells))


def ack(outcome: Outcome) -> bytes:
    """The 66B content: `01`, the gold after, the row count, then one 7B
    entry per sold row -- zero-padded to a multiple of 8."""
    out = bytearray(b"\x01")
    out += struct.pack("<I", outcome.gold_after)
    out += struct.pack("<H", len(outcome.sales))
    out += bytes(3)
    for sale in outcome.sales:
        out += struct.pack("<HIB", sale.slot, sale.left, 0)
    return bytes(out) + bytes(-len(out) % 8)


def frames(outcome: Outcome) -> list[tuple[frame.Opcode, bytes]]:
    """The three frames, in the reference's order."""
    return [(OPCODE, ack(outcome)),
            (refresh.OPCODE_SLOT,
             refresh.slot_frame(GOLD_LIST, outcome.records)),
            (refresh.OPCODE_BOARD, refresh.BOARD_AFTER_WRITE_BODY)]


def outcome_line(conn: int, outcome: Outcome) -> str:
    """The sale line: one clause per row, then the balance and the answer."""
    parts = [f"item {sale.item_id} ×{sale.count} from list 0 slot {sale.slot} "
             f"for {sale.price} gold ({sale.each} each), {sale.left} left"
             for sale in outcome.sales]
    return (f"conn={conn} sold " + "; ".join(parts)
            + f"; {outcome.gold_after} gold; answered with the ack + (0,14)×1")
