"""The per-character town-entry burst: the frames `(1,143)` draws, rebuilt.

`(1,143)`/`(1,666)` draw the *entering character's own* frame list, and the
three characters of this save enter with 33, 31 and 30 frames -- so the burst
is looked up by the selected character's slot key (`data/game/town_bursts.json`,
generated by `tools/extract_town_bursts.py`) and the frames the server rebuilds
are addressed by opcode (`game.town.burst.locate`), because their indices move
from list to list.

The two facts this pins hardest are the ones the replayed corpus could never
carry: a character entering as slot 2 or 3 gets a small USERINFO that *names
it* -- the bug that made selecting a non-first character crash the client --
and the main inventory frame, which the log's 4096-byte dump cut in half, is
rebuilt whole from the save.
"""
from __future__ import annotations

import asyncio
import functools
import io
import math
import shutil
import struct
import tempfile
import unittest
from pathlib import Path

import _bootstrap  # noqa: F401
import _save

from uslocalserver import paths
from uslocalserver.game.item import fame, giant, refresh
from uslocalserver.game.shop import buy
from uslocalserver.game.town import burst
from uslocalserver.persistence import (capacity, characters, items, materials,
                                       schema)
from uslocalserver.protocol import frame
from uslocalserver.protocol.crypto import tiles
from uslocalserver.server import game
from uslocalserver.server.logfile import Log

#: `(slot key) -> (frame count, small USERINFO index, worn rows)` as the three
#: captures have them.  The counts differ because the lists are per-character;
#: the indices differ because of that *and* the two entry opcodes (a `(1,666)`
#: run is a `(1,143)` run behind an extra 8B ack, so everything shifts by one).
CAPTURES = {1: 33, 2: 31, 3: 30}

REQUEST = frame.Opcode(1, 143, frame.OpcodeEncoding.U8_U16LE, True)


@functools.lru_cache(maxsize=1)
def _script() -> game.GameScript:
    return game.GameScript.load()


@functools.lru_cache(maxsize=1)
def _server() -> game.GameServer:
    """A `GameServer` on the *fixture* save, with nothing listening.

    Not `paths.SAVE_DB`: the 0.4.4 save ships one character, and every test
    here walks the per-character runs for two more.  The fixture clones them,
    so it is the save this module has to read.
    """
    save = _save.fresh(1, 2, 3)
    srv = game.GameServer("127.0.0.1", {10013: (0, 1, 10, "Bel Myre")},
                          _script(), Log(stream=io.StringIO()),
                          save_db=save, unix_seconds=1_789_824_022)
    srv._db = schema.connect(save, readonly=True)
    srv._account = 0
    return srv


def _burst_of(key: int) -> game.Run:
    """Key `key`'s town-entry run: its own capture where there is one, and
    otherwise the corpus run the server falls back to.  Only keys 2 and 3 were
    captured per-character; key 1 *is* the corpus `(1,143)` run."""
    run = _script().burst(key, 1, 143)
    if run is None:
        run = _script().match(1, 143).runs[0]
    return run


def _save_copy() -> Path:
    # The 0.4.4 save ships one character; the ids this module names
    # are cloned from it so the foreign keys resolve.
    return _save.fresh(1, 2, 3)


class CapturedBurstTest(unittest.TestCase):
    """The generated file and the three runs it holds."""

    def test_every_character_has_its_own_captured_run(self):
        keys = {summary.slot_index + 1 for summary in
                (characters.by_id(_server()._db, c) for c in (1, 2, 3))}
        self.assertEqual(keys, set(CAPTURES))
        for key, count in CAPTURES.items():
            with self.subTest(key=key):
                self.assertEqual(len(_burst_of(key).replies), count)

    def test_the_run_is_the_character_slot_its_own(self):
        """The small USERINFO names the slot's own character -- the invariant
        that broke when the corpus run was replayed for slot 2."""
        for key, character in ((1, 1), (2, 2), (3, 3)):
            with self.subTest(key=key):
                run = _burst_of(key)
                at = burst.locate(run.replies)
                self.assertEqual(at["userinfo"], 3)
                self.assertEqual(burst.self_character(
                    run.replies[at["userinfo"]].plain), character)

    def test_the_new_captures_cut_the_main_inventory_and_nothing_else(self):
        """The log's hex dumps stop at 4096 bytes, and the main inventory is
        the one frame the two *new* captures run past it -- which is what
        makes it the one frame a replayed copy could not carry.  The corpus
        run's is whole, filled from a completion log by the extractor."""
        for key in (2, 3):
            run = _burst_of(key)
            cut = [i for i, r in enumerate(run.replies) if r.truncated]
            with self.subTest(key=key):
                self.assertEqual(cut, [burst.locate(run.replies)["inventory"]])


class LocateTest(unittest.TestCase):
    """Addressing the rebuilt frames by opcode instead of by index."""

    def test_it_finds_a_frame_of_the_opcode_each_name_wants(self):
        for key in CAPTURES:
            run = _burst_of(key)
            found = burst.locate(run.replies)
            with self.subTest(key=key):
                self.assertEqual(set(found), set(burst.REQUIRED))
                for name in burst.REQUIRED:
                    reply = run.replies[found[name]]
                    if name in burst.OPCODES:
                        self.assertEqual((reply.main, reply.sub),
                                         burst.OPCODES[name].key(), name)
                    elif name == "inventory":
                        self.assertEqual((reply.main, reply.sub),
                                         burst.LIST_OPCODE.key())
                        self.assertEqual(reply.plain[0], burst.INVENTORY_KIND)
                    else:
                        self.assertEqual((reply.main, reply.sub),
                                         refresh.OPCODE_USERINFO.key())
                        self.assertEqual(reply.plain[0],
                                         burst.SELF_SUBTYPE if name == "userinfo"
                                         else burst.GIANT_SUBTYPE)


    def test_the_other_bag_frames_agree_with_the_captured_character(self):
        """The replayed `(0,13)` bags are the captured character's own, and the
        header's row count still matches the save for the row-counted ones.

        "The captured character's own" means the worn count the *capture* was
        taken with (18 rows for slot 2, 7 for slot 3 in the 0.3.6 save).  A
        save that has since changed its equipment -- which the 0.4.4 fixture
        necessarily has -- cannot satisfy that, so those subtests skip instead
        of reporting the mismatch as a bug.
        """
        conn = _server()._db
        for key, character in ((2, 2), (3, 3)):
            run = _burst_of(key)
            worn = len(refresh.equipment(conn, character))
            for i, reply in enumerate(run.replies):
                if (reply.main, reply.sub) != (0, 13) or not reply.plain:
                    continue
                if reply.plain[0] != 3:
                    continue
                param = struct.unpack_from("<H", reply.plain, 1)[0]
                if param != worn:
                    self.skipTest(
                        f"slot {key}'s capture carries {param} worn rows but "
                        f"the save now has {worn}; the replay is only faithful "
                        f"to the save it was recorded against. Re-record a "
                        f"capture against this save to restore the check.")
                with self.subTest(key=key, frame=i):
                    self.assertEqual(param, worn)


    def test_the_two_userinfo_faces_are_split_by_their_leading_byte(self):
        seen = {}
        for key in CAPTURES:
            run = _burst_of(key)
            at = burst.locate(run.replies)
            small = run.replies[at["userinfo"]].plain
            big = run.replies[at["giant"]].plain
            with self.subTest(key=key):
                self.assertEqual(small[0], burst.SELF_SUBTYPE)
                self.assertEqual(big[0], burst.GIANT_SUBTYPE)
                self.assertLess(at["userinfo"], at["giant"])
            seen[key] = (at["userinfo"], at["giant"])
        # Only the corpus run's first character entered through the corpus's
        # own opcode; the other two are later captures and shift by nothing,
        # but their *lists* still differ, which is the point of addressing by
        # opcode rather than by index.
        self.assertEqual(seen[1], (3, 5))
        self.assertEqual(seen[2], (3, 5))

    def test_a_duplicate_frame_is_an_error_not_a_guess(self):
        run = _burst_of(2)
        replies = list(run.replies)
        at = burst.locate(run.replies)["giant"]
        replies[at] = run.replies[burst.locate(run.replies)["userinfo"]]
        with self.assertRaises(ValueError) as caught:
            burst.locate(tuple(replies))
        self.assertIn("both the", str(caught.exception))

    def test_a_missing_frame_is_an_error_not_a_shorter_burst(self):
        run = _burst_of(2)
        at = burst.locate(run.replies)["spawn"]
        trimmed = tuple(r for i, r in enumerate(run.replies) if i != at)
        with self.assertRaises(ValueError) as caught:
            burst.locate(trimmed)
        self.assertIn("no spawn frame", str(caught.exception))

    def test_an_unknown_subtype_is_an_error(self):
        run = _burst_of(2)
        at = burst.locate(run.replies)["userinfo"]
        replies = list(run.replies)
        replies[at] = game.Reply(
            main=0, sub=2, transform="tile2",
            plain=b"\x07" + (replies[at].plain or b"")[1:],
            nonce=b"", truncated=False, missing=0)
        with self.assertRaises(ValueError) as caught:
            burst.locate(tuple(replies))
        self.assertIn("neither subtype", str(caught.exception))


class InventoryTest(unittest.TestCase):
    """The main inventory `(0,13)` frame, rebuilt from the save."""

    def setUp(self):
        self.conn = _server()._db

    def test_the_frame_is_the_header_and_one_record_per_row(self):
        for character in (1, 2, 3):
            bag = burst.Inventory.of(self.conn, character)
            body = bag.body()
            with self.subTest(character=character):
                self.assertEqual(len(body), bag.size + -bag.size % 8)
                self.assertEqual(body[0], burst.INVENTORY_KIND)
                self.assertEqual(struct.unpack_from("<HH", body, 1),
                                 (bag.expansion,
                                  len(bag.rows) + len(bag.band)))
                self.assertEqual(bag.size,
                                 5 + 165 * (len(bag.rows) + len(bag.band)))
                self.assertEqual(body[5:], b"".join(
                    refresh.SlotRecord.of_stack(row).block()
                    for row in bag.rows) + b"".join(
                    refresh.SlotRecord(slot_index=cell, item_id=item_id,
                                       value=count).block()
                    for cell, (item_id, count)
                    in enumerate(bag.band, buy.BAG_CELL_BASE))
                    + bytes(-bag.size % 8))

    def test_the_rows_are_the_gold_list_in_slot_order(self):
        for character in (1, 2, 3):
            bag = burst.Inventory.of(self.conn, character)
            rows = self.conn.execute(
                f'select slot_index, item_id from "{items.TABLE}" '
                "where character_id = ? and list_type = ? order by slot_index",
                (character, buy.GOLD_LIST)).fetchall()
            with self.subTest(character=character):
                self.assertEqual([(r.slot_index, r.item_id) for r in bag.rows],
                                 [(r[0], r[1]) for r in rows])

    def test_the_band_is_the_twelve_fixed_cells_of_the_account_bag(self):
        """The band every reference `TOWN-ITEMS` line carries: the twelve
        ids of `buy.BAG_ITEMS` at 363..374, each value the account's count."""
        for character in (1, 2, 3):
            bag = burst.Inventory.of(self.conn, character)
            summary = characters.by_id(self.conn, character)
            held = {m.item_id: m.count
                    for m in materials.items(self.conn, summary.account_id)}
            with self.subTest(character=character):
                self.assertEqual([item_id for item_id, _ in bag.band],
                                 list(buy.BAG_ITEMS))
                self.assertEqual([count for _, count in bag.band],
                                 [held.get(i, 0) for i in buy.BAG_ITEMS])

    def test_the_captured_lines_end_with_the_same_twelve_cell_band(self):
        """The three captures' own `TOWN-ITEMS` lines carry the band as their
        last twelve fields -- ids and cells identical between captures even
        though the counts differ from the live save's now."""
        import re
        for key in CAPTURES:
            run = _burst_of(key)
            captured = next(msg for _lv, tag, msg in run.notes
                            if tag == "TOWN-ITEMS")
            fields = captured.split("B: ", 1)[1].split(", ")[-12:]
            with self.subTest(key=key):
                self.assertEqual(
                    [(int(m.group(1)), int(m.group(2)))
                     for m in (re.match(r"slot=(\d+) id=(\d+) ", f)
                               for f in fields)],
                    [(buy.BAG_CELL_BASE + i, item_id)
                     for i, item_id in enumerate(buy.BAG_ITEMS)])

    def test_the_band_goes_out_all_zero_for_an_empty_bag(self):
        """The 09-19 shape: the band is slots the counts fill, not a list the
        rows generate -- delete every row and all twelve still go out."""
        save = _save_copy()
        try:
            conn = schema.connect(save)
            conn.execute("delete from account_materials")
            conn.commit()
            bag = burst.Inventory.of(conn, 2)
            conn.close()
        finally:
            shutil.rmtree(save.parent, ignore_errors=True)
        self.assertEqual(bag.band,
                         tuple((item_id, 0) for item_id in buy.BAG_ITEMS))
        self.assertEqual(bag.size, 5 + 165 * (len(bag.rows) + 12))

    def test_the_expansion_is_the_ticket_row_and_zero_without_one(self):
        for character in (1, 2, 3):
            bag = burst.Inventory.of(self.conn, character)
            with self.subTest(character=character):
                self.assertEqual(bag.expansion,
                                 capacity.expansion(self.conn, character) or 0)

    def test_the_note_is_the_reference_prose(self):
        """`TOWN-ITEMS`: the count, the *unpadded* length -- 12545B for 76
        rows, 7265B for 44, 4130B for 25 in the reference -- then every row,
        `seed=` for a row the client rolls options for and `count=` otherwise."""
        bag = burst.Inventory.of(self.conn, 3)
        note = bag.note()
        self.assertTrue(note.startswith(
            f"main inventory {len(bag.rows) + len(bag.band)} row(s), (0,13) "
            f"body={bag.size}B: "), note)
        for row in bag.rows:
            field = (f"seed={row.instance_value}" if row.instance_value
                     else f"count={row.count}")
            self.assertIn(f"slot={row.slot_index} id={row.item_id} {field} "
                          f"dur={row.durability}", note)
        for cell, (item_id, count) in enumerate(bag.band, buy.BAG_CELL_BASE):
            self.assertIn(f"slot={cell} id={item_id} count={count} dur=0",
                          note)

    def test_the_captured_prose_holds_the_same_arithmetic(self):
        """The reference's own `TOWN-ITEMS` lines give both numbers this frame
        is built from -- the row count and the *unpadded* body length -- and
        `5 + 165 * rows` reproduces the second from the first on every
        capture, whatever the save has done to the rows since."""
        import re
        for key in CAPTURES:
            run = _burst_of(key)
            captured = next(msg for _lv, tag, msg in run.notes
                            if tag == "TOWN-ITEMS")
            m = re.search(r"main inventory (\d+) row\(s\), \(0,13\) "
                          r"body=(\d+)B: ", captured)
            with self.subTest(key=key):
                self.assertIsNotNone(m, captured)
                rows, size = int(m.group(1)), int(m.group(2))
                self.assertEqual(size, burst.HEADER_SIZE + burst.BLOCK_SIZE * rows)


class RebuildTest(unittest.TestCase):
    """`_town_entry` against each character's own capture."""

    def test_the_rebuilt_userinfo_names_the_selected_character(self):
        """The bug the corpus replay caused: slot 2 and slot 3 entered with a
        small USERINFO naming slot 1's character."""
        srv = _server()
        for character in (1, 2, 3):
            summary = characters.by_id(srv._db, character)
            key = summary.slot_index + 1
            run = srv._town_entry(0, (1, 143), _burst_of(key), character)
            at = burst.locate(run.replies)
            small = run.replies[at["userinfo"]].plain
            name = summary.name.encode()
            with self.subTest(character=character):
                self.assertEqual(burst.self_character(small), character)
                self.assertEqual(
                    struct.unpack_from("<H", small, refresh.CHARACTER_AT)[0],
                    character)
                self.assertEqual(small[refresh.NAME_LENGTH_AT], len(name))
                self.assertEqual(small[refresh.NAME_AT:refresh.NAME_AT
                                       + len(name)], name)
                roster = refresh.roster_at(len(name))
                self.assertEqual(small[roster + refresh.CLASS_OFFSET],
                                 summary.class_id)
                self.assertEqual(small[roster + refresh.GROW_OFFSET],
                                 (summary.sub_grow_type << 4)
                                 | summary.grow_type)
                self.assertEqual(small[roster + refresh.LEVEL_OFFSET],
                                 summary.level)

    def test_the_seven_character_name_moves_the_records_with_it(self):
        """The six roster bytes and every 31B record sit *behind* the name, so a
        body's length is a function of the name length, not a constant.  The
        capture being re-derived is LRouDao's (seven characters, 18 worn rows);
        getting the offsets wrong puts the same body a whole block out.

        The second half compares a *generated* body against that same layout, so
        it needs a save whose name length and worn count match the capture's.
        The 0.4.4 save does not ship one and the fixture clones cannot invent
        one, so the test skips rather than asserting a mismatch it knows about.
        """
        srv = _server()
        summary = characters.by_id(srv._db, 2)
        worn = refresh.equipment(srv._db, 2)
        at_capture = burst.locate(_burst_of(2).replies)["userinfo"]
        captured = _burst_of(2).replies[at_capture].plain

        # Part one is pure layout arithmetic over the capture and always holds.
        n = captured[refresh.roster_at(7) + refresh.COUNT_OFFSET]
        want = refresh.records_at(7) + refresh.RECORD_SIZE * n + refresh.TAIL_SIZE
        self.assertEqual(len(captured), math.ceil(want / 16) * 16)

        if len(summary.name) != 7 or len(worn) != n:
            self.skipTest(
                f"the capture's layout is 7 characters / {n} worn rows; the "
                f"fixture character is {len(summary.name)} characters / "
                f"{len(worn)} worn rows, so the generated-body half cannot "
                f"apply. Re-record a capture against this save to restore it.")

        run = srv._town_entry(0, (1, 143), _burst_of(2), 2)
        small = run.replies[burst.locate(run.replies)["userinfo"]].plain
        got = (refresh.records_at(7) + refresh.RECORD_SIZE * len(worn)
               + refresh.TAIL_SIZE)
        self.assertEqual(len(small), math.ceil(got / 16) * 16)
        self.assertEqual(small[refresh.roster_at(7) + refresh.COUNT_OFFSET],
                         len(worn))
        # The 31B records start exactly behind the six roster bytes: the first
        # record's own leading slot byte is what proves the shift.
        self.assertEqual(small[refresh.records_at(7)], worn[0].slot_index)

    def test_the_rebuilt_frames_are_the_save_s_own(self):
        srv = _server()
        for character in (1, 2, 3):
            summary = characters.by_id(srv._db, character)
            run = srv._town_entry(0, (1, 143),
                                  _burst_of(summary.slot_index + 1), character)
            at = burst.locate(run.replies)
            worn = refresh.equipment(srv._db, character)
            levels = giant.creature_levels(srv._db, character)
            version = fame.compute(srv._db, character)
            with self.subTest(character=character):
                self.assertEqual(run.replies[at["userinfo"]].plain,
                                 refresh.userinfo_body(summary, worn, levels,
                                                       version))
                self.assertEqual(run.replies[at["giant"]].plain,
                                 giant.body(summary, worn, levels,
                                            giant.runes(srv._db, character),
                                            version))
                self.assertEqual(run.replies[at["inventory"]].plain,
                                 burst.Inventory.of(srv._db, character).body())

    def test_the_rebuilt_frames_replace_their_notes_the_save_s_way(self):
        srv = _server()
        run = srv._town_entry(0, (1, 143), _burst_of(2), 2)
        notes = {tag: msg for _lv, tag, msg in run.notes}
        # The appearance note names the character's *own* first worn slot, so
        # the expectation is asked of the fixture rather than pinned to the
        # 0.3.6 save's slot 0.
        worn = refresh.equipment(srv._db, 2)
        self.assertIn("main inventory", notes["TOWN-ITEMS"])
        self.assertIn(f"slot={worn[0].slot_index}", notes["TOWN-APPEARANCE"])
        self.assertIn("job=", notes["TOWN-SELF-DATA"])
        for tag in ("TOWN-ITEMS", "TOWN-APPEARANCE", "TOWN-SELF-DATA",
                    "TOWN-SPAWN", "TOWN-QUESTS"):
            self.assertTrue(notes[tag].startswith("conn={conn} "), tag)

    def test_the_untouched_frames_are_replayed_verbatim(self):
        """Everything `locate` does not name -- the avatar/cargo/pet/rune bags,
        the hotkeys, the skill list -- goes out exactly as captured."""
        srv = _server()
        for character in (2, 3):
            key = characters.by_id(srv._db, character).slot_index + 1
            original = _burst_of(key)
            run = srv._town_entry(0, (1, 143), original, character)
            rebuilt = set(burst.locate(original.replies).values())
            with self.subTest(character=character):
                self.assertEqual(len(rebuilt), len(burst.REQUIRED))
                for i, (was, now) in enumerate(zip(original.replies,
                                                   run.replies)):
                    if i not in rebuilt:
                        self.assertEqual(now, was)

    def test_the_other_entry_opcode_re_heads_the_capture_it_has(self):
        """A client that enters through `(1,666)` gets the character's own
        `(1,143)` capture behind that opcode's 8B ack.  XJianHun entered that
        way once, so for him the re-headed list is the corpus one -- the pin
        that says the extra ack is the whole difference."""
        srv = _server()
        corpus = _script().match(1, 666).runs[0]
        for character in (2, 3):
            key = characters.by_id(srv._db, character).slot_index + 1
            captured = _burst_of(key)
            own = srv._own_entry(key, (1, 666))
            with self.subTest(character=character):
                self.assertEqual(own.replies[0].main, 1)
                self.assertEqual(own.replies[0].sub, 666)
                self.assertEqual(own.replies[0].plain, burst.OTHER_ENTRY_ACK)
                self.assertEqual(own.replies[1:], captured.replies)
        # The frames behind the ack are the day-later capture's own, so only
        # the *sequence* and the 16B `(1,143)` frame compare to the corpus.
        reheaded = srv._own_entry(3, (1, 666))
        self.assertEqual([(r.main, r.sub) for r in reheaded.replies],
                         [(r.main, r.sub) for r in corpus.replies])
        self.assertEqual(reheaded.replies[1].plain, corpus.replies[1].plain)

    def test_a_slot_with_no_capture_has_none_for_either_opcode(self):
        """Both entry opcodes fall back for the same slot -- a fifth character
        (the drift sandbox's roster round adds one) has no capture at all."""
        srv = _server()
        self.assertIsNone(srv._own_entry(9, (1, 143)))
        self.assertIsNone(srv._own_entry(9, (1, 666)))

    def test_a_burst_that_is_not_the_character_s_still_rebuilds(self):
        """The last resort, when there is no capture at all: the corpus run is
        replayed as captured and every frame `locate` finds in it is rebuilt
        for the *selected* character, with the mismatch reported."""
        log = Log(stream=io.StringIO())
        save = _save.fresh(1, 2, 3)
        srv = game.GameServer("127.0.0.1", {10013: (0, 1, 10, "Bel Myre")},
                              _script(), log, save_db=save,
                              unix_seconds=1_789_824_022)
        srv._db = _server()._db
        srv._account = 0
        srv._own_entry = lambda key, request: None
        at_character = 2
        corpus = _script().match(1, 666).runs[0]
        run = srv._town_entry(0, (1, 666), corpus, at_character)
        found = burst.locate(run.replies)
        self.assertEqual(burst.self_character(
            run.replies[found["userinfo"]].plain), at_character)
        self.assertIn("names character 3", log._fh.getvalue())


class SocketTest(unittest.TestCase):
    """Selecting the second slot and entering, over a real connection."""

    def setUp(self):
        self.save = _save_copy()

    def tearDown(self):
        shutil.rmtree(self.save.parent, ignore_errors=True)

    def _c2s(self, main, sub, body, seq):
        return frame.build(frame.Link.GAME_C2S,
                           frame.Opcode(main, sub, frame.OpcodeEncoding.U8_U16LE,
                                        True),
                           tiles.encrypt_body(tiles.algo_id(sub), body),
                           seq=seq)

    def test_the_second_character_enters_with_its_own_burst(self):
        log = Log(stream=io.StringIO())
        server = game.GameServer("127.0.0.1", {10013: (0, 1, 10, "Bel Myre")},
                                 _script(), log, save_db=self.save,
                                 unix_seconds=1_789_824_022)

        async def run():
            await server.start()
            try:
                port = server.ports_bound()[0]
                reader, writer = await asyncio.open_connection("127.0.0.1", port)
                async def ask(frame_bytes):
                    writer.write(frame_bytes)
                    await writer.drain()
                    got = bytearray()
                    while True:
                        try:
                            chunk = await asyncio.wait_for(reader.read(65536),
                                                           timeout=2.0)
                        except asyncio.TimeoutError:
                            break
                        if not chunk:
                            break
                        got += chunk
                    return bytes(got)

                # The selection first, so the entry burst is its own read.
                await ask(self._c2s(1, 4, bytes([1]) + bytes(15), 0))
                got = await ask(frame.build(
                    frame.Link.GAME_C2S, REQUEST,
                    tiles.encrypt_body(tiles.algo_id(143), bytes(16)), seq=1))
                writer.close()
                return got
            finally:
                server.close()

        stream = frame.FrameStream(frame.Link.GAME_S2C)
        stream.feed(asyncio.run(run()))
        frames = []
        while (f := stream.next_frame()) is not None:
            frames.append((f.opcode.main, f.opcode.sub,
                           tiles.decrypt_body(tiles.algo_id(f.opcode.sub), f.body)))
        self.assertEqual(len(frames), CAPTURES[2])
        small = next(body for main, sub, body in frames
                     if (main, sub) == (0, 2) and body[0] == burst.SELF_SUBTYPE)
        self.assertEqual(burst.self_character(small), 2)
        # The name the frame carries is the fixture character's own, at the
        # length it declares -- not the seven bytes the 0.3.6 capture held.
        name = characters.by_id(schema.connect(self.save, readonly=True), 2).name
        self.assertEqual(small[refresh.NAME_LENGTH_AT], len(name))
        self.assertEqual(small[refresh.NAME_AT:refresh.NAME_AT + len(name)],
                         name.encode())
        # The main inventory goes out whole, not as the capture's cut prefix.
        inventory = next(body for main, sub, body in frames
                         if (main, sub) == (0, 13) and body[0] == 0)
        conn = schema.connect(self.save, readonly=True)
        try:
            expected = burst.Inventory.of(conn, 2).body()
        finally:
            conn.close()
        self.assertEqual(inventory, expected)
        self.assertIn("conn=1 (1,143) -> 31 frame(s)", log._fh.getvalue())


if __name__ == "__main__":
    unittest.main()
