# Generated by tools/gen_models.py -- do not edit, re-run the tool.
"""Typed rows for the 36 record sets among the 69 content tables.

A field's type is the union over every record in its set, never the first
record.  Two things stop the union from narrowing to a single type and get
a `# NEEDS-REVIEW` marker instead of a guess: `Any` (usually a key seen in
fewer than two records) and a genuine union, so that the fields whose shape
is unsettled stay greppable.  Fields absent from some records are optional,
and `load` supplies None for them.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping


def _coerce(value: Any) -> Any:
    """JSON arrays are lists; the annotations say tuple."""
    if isinstance(value, list):
        return tuple(_coerce(v) for v in value)
    if isinstance(value, dict):
        return {k: _coerce(v) for k, v in value.items()}
    return value


class Record:
    """Base of the generated rows; every subclass is frozen.

    Not slotted on purpose: on 3.11 `slots=True` rewrites the class and
    leaves the frozen guard raising TypeError instead of
    FrozenInstanceError, which is a trap for anyone catching the latter.
    """

    @classmethod
    def load(cls, raw: Mapping[str, Any]):
        """One record; keys the class does not declare are dropped."""
        return cls(**{name: _coerce(raw.get(name))
                      for name in cls.__dataclass_fields__})


# buff_swap.branches
# list of 67 records
@dataclass(frozen=True)
class BuffSwapBranchesRow(Record):
    job: int
    grow: int
    skills: tuple[int, ...]


# card_rewards.dungeons
# mapping of 3244 records
@dataclass(frozen=True)
class CardRewardsDungeonsRow(Record):
    type: int | None
    disabled: bool
    noGold: bool
    typeName: str


# creature_content.creatures
# mapping of 3007 records
@dataclass(frozen=True)
class CreatureContentCreaturesRow(Record):
    path: str
    subType: int
    output: int
    minimumLevel: int


# dungeon_content.dungeons
# list of 3244 records
@dataclass(frozen=True)
class DungeonContentDungeonsRow(Record):
    minLevel: int | None
    basisLevel: int | None
    id: int
    difficulty: tuple[int, ...] | None
    questList: tuple[int, ...] | None
    mazes: tuple[dict[str, Any], ...] | None  # NEEDS-REVIEW: elements mixed list|str
    dontKillMobWhenBossDies: bool | None


# dungeon_list.dungeons
# list of 3244 records
@dataclass(frozen=True)
class DungeonListDungeonsRow(Record):
    id: int
    path: str


# dungeon_worldmap.gates
# list of 389 records
@dataclass(frozen=True)
class DungeonWorldmapGatesRow(Record):
    townId: int
    areaId: int
    worldmapId: int


# dungeon_worldmap.worldmaps
# list of 224 records
@dataclass(frozen=True)
class DungeonWorldmapWorldmapsRow(Record):
    id: int
    name: str
    dungeonIds: tuple[int, ...]


# dusky_island_operations.operations
# list of 29 records
@dataclass(frozen=True)
class DuskyIslandOperationsOperationsRow(Record):
    id: int
    type: int
    unshackled: bool
    pool: int
    weight: int
    fixedValue: int
    minimum: float
    maximum: float
    step: int
    fame: int


# dye_content.dyes
# mapping of 75 records
@dataclass(frozen=True)
class DyeContentDyesRow(Record):
    source: str
    type: int
    minimumLevel: int
    colors: tuple[tuple[int, ...], ...]


# enchant_emblem.cards
# mapping of 21635 records
@dataclass(frozen=True)
class EnchantEmblemCardsRow(Record):
    types: tuple[str, ...]
    levels: dict[str, int]


# enchant_emblem.beads
# mapping of 3773 records
@dataclass(frozen=True)
class EnchantEmblemBeadsRow(Record):
    cards: tuple[tuple[int, ...], ...]
    targets: tuple[int, ...]
    worlds: tuple[str, ...]
    minimumLevel: int


# hell_party.dungeons
# list of 36 records
@dataclass(frozen=True)
class HellPartyDungeonsRow(Record):
    id: int
    rooms: tuple[dict[str, Any], ...]  # NEEDS-REVIEW: elements mixed int|list|str


# hell_party.maps
# list of 34 records
@dataclass(frozen=True)
class HellPartyMapsRow(Record):
    id: int
    type: str
    monsters: tuple[tuple[int, ...], ...]
    monsterFlags: tuple[tuple[str, ...], ...]
    monsterLevelValues: tuple[int, ...]


# hell_party.groups
# mapping of 97 records
@dataclass(frozen=True)
class HellPartyGroupsRow(Record):
    A: tuple[dict[str, int], ...] | None
    B: tuple[dict[str, int], ...] | None


# inventory_tickets.tickets
# mapping of 92 records
@dataclass(frozen=True)
class InventoryTicketsTicketsRow(Record):
    source: str
    target: int
    minimumLevel: int


# magic_seal_content.options
# mapping of 101 records
@dataclass(frozen=True)
class MagicSealContentOptionsRow(Record):
    type: int
    levels: tuple[tuple[int, ...], ...]


# map_content.maps
# list of 17081 records
@dataclass(frozen=True)
class MapContentMapsRow(Record):
    type: str
    monsters: tuple[tuple[int, ...], ...] | None
    monsterFlags: tuple[tuple[str, ...], ...] | None
    monsterLevelValues: tuple[int, ...] | None
    id: int
    startArea: tuple[int, ...] | None
    monsterTeams: tuple[int, ...] | None
    monsterParseError: str | None
    elevatorLevel: int | None
    disableRebirth: bool | None
    autoMove: dict[str, int] | None


# monster_drops.monsters
# mapping of 13731 records
@dataclass(frozen=True)
class MonsterDropsMonstersRow(Record):
    minLevel: int
    maxLevel: int
    pool: tuple[tuple[int, ...], ...]


# npc_shop_content.shops
# mapping of 1056 records
@dataclass(frozen=True)
class NpcShopContentShopsRow(Record):
    npc: int
    type: str
    items: tuple[int, ...]


# npc_shop_rules.shops
# mapping of 1057 records
@dataclass(frozen=True)
class NpcShopRulesShopsRow(Record):
    npc: int
    type: str
    items: tuple[int, ...]
    path: str
    blocked: tuple[str, ...]
    multiBuyLimit: int


# npc_shop_rules.items
# mapping of 10238 records
@dataclass(frozen=True)
class NpcShopRulesItemsRow(Record):
    gold: int
    materials: tuple[dict[str, int], ...]
    limits: tuple[dict[str, int | str], ...]  # NEEDS-REVIEW: elements values union of int | str
    version: int
    blocked: tuple[str, ...]
    path: str


# package_content.packages
# mapping of 54030 records
@dataclass(frozen=True)
class PackageContentPackagesRow(Record):
    type: str
    fixed: tuple[tuple[int, ...], ...] | None
    groups: tuple[tuple[Any, ...], ...] | None  # NEEDS-REVIEW: elements mixed int|list
    select: int | None
    dimensions: tuple[int, ...] | None
    categories: dict[str, tuple[tuple[int, ...], ...]] | None
    categoryHeader: tuple[int, ...] | None
    costs: tuple[tuple[int, ...], ...] | None


# pot_content.items
# mapping of 2003 records
@dataclass(frozen=True)
class PotContentItemsRow(Record):
    path: str
    type: str
    rewards: tuple[tuple[int, ...], ...]


# progression_items.items
# list of 20 records
@dataclass(frozen=True)
class ProgressionItemsItemsRow(Record):
    itemId: int
    minLevel: int
    maxLevel: int
    experience: int
    targetLevel: int
    sp: int
    tp: int
    seriaOnly: bool
    source: str


# quest_content.quests
# mapping of 3217 records
@dataclass(frozen=True)
class QuestContentQuestsRow(Record):
    level: int
    levelMax: int
    grade: str
    questType: str
    subType: int
    monsterRewardItem: tuple[int, ...]
    enemyRewardItem: tuple[int, ...]
    preRequiredQuests: tuple[int, ...]
    relationQuests: tuple[int, ...]
    targets: tuple[int, ...]
    dungeonInfo: tuple[int, ...]
    jobs: tuple[str, ...]
    growTypes: tuple[int, ...]
    targetCharacters: tuple[dict[str, int | str], ...]  # NEEDS-REVIEW: elements values union of int | str
    difficulty: str
    rewardType: str
    goldMultiple: int
    ignoreLevel: bool
    exposedByNpc: int
    isEvent: bool
    hasCreatureRequirement: bool
    hasExpertRequirement: bool
    items: tuple[tuple[int, ...], ...] | None
    preRequiredQuestGroups: tuple[tuple[int, ...], ...] | None
    collisionQuests: tuple[int, ...] | None
    selection: tuple[tuple[int, ...], ...] | None
    acceptItems: tuple[tuple[int, ...], ...] | None


# quest_npc_ranges (root)
# list of 21 records
@dataclass(frozen=True)
class QuestNpcRangesRow(Record):
    questId: int
    npcId: int
    rangeX: int
    rangeY: int
    locations: tuple[dict[str, int], ...]


# scenario_visits (root)
# list of 21 records
@dataclass(frozen=True)
class ScenarioVisitsRow(Record):
    dungeon: int
    maze: int
    quest: int
    x: int
    y: int
    baseMap: int
    layers: tuple[int, ...]
    entryDeath: int
    exitDeath: int
    evidence: tuple[str, ...]
    apcs: Any  # NEEDS-REVIEW: seen in 1/21 records


# skin_slot_tickets (root)
# list of 38 records
@dataclass(frozen=True)
class SkinSlotTicketsRow(Record):
    Id: int
    Slot: int
    MinimumLevel: int
    Source: str


# story_positions (root)
# list of 440 records
@dataclass(frozen=True)
class StoryPositionsRow(Record):
    dungeon: int
    maze: int
    cellX: int
    cellY: int
    source: int
    target: int
    x: int
    y: int
    bounds: tuple[int, ...]
    evidence: tuple[str, ...]


# teleport_potions.npcTargets
# list of 218 records
@dataclass(frozen=True)
class TeleportPotionsNpcTargetsRow(Record):
    id: int
    area: int
    x: int
    y: int
    minimumLevel: int
    requiredQuests: tuple[int, ...]
    excludedQuests: tuple[int, ...]
    source: str
    npcIds: tuple[int, ...]
    maps: tuple[str, ...]


# teleport_potions.selectionAreas
# list of 94 records
@dataclass(frozen=True)
class TeleportPotionsSelectionAreasRow(Record):
    id: int
    area: int
    minimumLevel: int
    requiredQuests: tuple[int, ...]
    excludedQuests: tuple[int, ...]
    rectangle: tuple[int, ...]
    source: str
    townSource: str


# teleport_potions.selectionNpcs
# list of 248 records
@dataclass(frozen=True)
class TeleportPotionsSelectionNpcsRow(Record):
    id: int
    area: int
    minimumLevel: int
    requiredQuests: tuple[int, ...]
    excludedQuests: tuple[int, ...]
    source: str
    townSource: str
    x: int
    y: int
    npcIds: tuple[int, ...]


# teleport_potions.skippedSelectionAreas
# list of 32 records
@dataclass(frozen=True)
class TeleportPotionsSkippedSelectionAreasRow(Record):
    town: int | None
    area: int | None
    source: str
    reason: str


# town_quest_gates (root)
# list of 24 records
@dataclass(frozen=True)
class TownQuestGatesRow(Record):
    townId: int
    areaId: int
    map: str
    questIds: tuple[int, ...]


# tutorial_apcs (root)
# list of 22 records
@dataclass(frozen=True)
class TutorialApcsRow(Record):
    map: int
    apcs: tuple[dict[str, int], ...]


# upgrade_tickets (root)
# list of 1894 records
@dataclass(frozen=True)
class UpgradeTicketsRow(Record):
    Id: int
    Mode: int
    Target: int
    Percent: int
    ApplyMode: str
    Limit: int
    MinimumEquipment: int
    MaximumEquipment: int
    AllowedIds: tuple[int, ...]
    MinimumCharacter: int
    MaximumCharacter: int
    Job: int
    Types: tuple[str, ...]
    Parts: tuple[str, ...]
    ExcludedRarities: tuple[int, ...]
    Source: str
    RandomLevels: tuple[int, ...]
    RandomWeights: tuple[int, ...]
    AllowedRarities: tuple[int, ...]


# 6 of the 223 fields above carry NEEDS-REVIEW (4 of them Any).
