"""The opcode registry: loader and query API.

`data/protocol/opcodes.json` is generated by `tools/gen_opcodes.py` from the
reference server's logs; this module only reads it.  Every entry keeps the
evidence that put it there, so a name or a direction can always be traced
back to a log line.  That tool's docstring lists the six shapes that count as
evidence, and the three traps they are guarded against (cell coordinates
sitting where opcodes sit, cell transitions looking like response refs, and
tags sharing a suffix).

    rec = lookup(1, 16)      # None when the opcode was never observed
    rec.name                 # "DUNGEON-ENTER", or None
    rec.directions           # ("c2s",) / ("s2c",) / both, never empty
    rec.handled              # True = dispatched, False = UNHANDLED, None = unknown

    unhandled()              # the not-yet-implemented list, busiest first
    census()                 # counts per direction / evidence source

Channel opcodes live in their own namespace (`channel_lookup(raw)`): their
`main` is the unexplained 0x7c prefix, so `lookup` refuses to mix them with
the game namespace where main is a real direction/response flag.
"""
from __future__ import annotations

import functools
import json
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final, Mapping

from .. import paths

#: Evidence source -> what a hit means.  Kept here so callers can label them.
SOURCE_NOTES: Final[dict[str, str]] = {
    "packet-c2s": "explicit opcode on a DEBUG PACKET C->S line",
    "packet-s2c": "decoded from a DEBUG PACKET S->C frame header",
    "dispatch": "a handler ran (DEBUG DISPATCH)",
    "unhandled": "received with no handler (WARN UNHANDLED)",
    "seen": "listed in a session's INFO GAME seen=[...]",
    "response": "referenced as a response frame (-> (m,s) NB)",
    "tagged": "logged by a descriptive tag, e.g. TOWN-QUEST-STATE",
}


@dataclass(frozen=True, slots=True)
class OpcodeRecord:
    main: int
    sub: int
    name: str | None
    directions: tuple[str, ...]
    evidence: Mapping[str, int]
    handled: bool | None
    responses: Mapping[int, int] = field(default_factory=dict)
    named_by: tuple[str, ...] = ()
    logged_by: tuple[str, ...] = ()

    @property
    def key(self) -> tuple[int, int]:
        return (self.main, self.sub)

    @property
    def hits(self) -> int:
        return sum(self.evidence.values())

    def __str__(self) -> str:
        bits = [f"({self.main},{self.sub})"]
        if self.name:
            bits.append(self.name)
        bits.append("+".join(self.directions))
        if self.handled is False:
            bits.append("UNHANDLED")
        return " ".join(bits)


@dataclass(frozen=True, slots=True)
class Census:
    game: int
    channel: int
    by_direction: Mapping[str, int]
    by_evidence: Mapping[str, int]
    named: int
    dispatched: int
    unhandled: int
    unknown: int
    uncorroborated_tags: tuple[str, ...]

    def report(self) -> str:
        lines = [
            f"game opcodes      {self.game}   channel opcodes {self.channel}",
            f"directions        {dict(self.by_direction)}",
            f"evidence          {dict(self.by_evidence)}",
            f"named             {self.named}",
            f"dispatched        {self.dispatched}",
            f"unhandled         {self.unhandled}",
            f"handler unknown   {self.unknown}",
        ]
        if self.uncorroborated_tags:
            lines.append(f"uncorroborated    {', '.join(self.uncorroborated_tags)}")
        return "\n".join(lines)


def _record(raw: Mapping) -> OpcodeRecord:
    return OpcodeRecord(
        main=int(raw["main"]),
        sub=int(raw["sub"]),
        name=raw["name"],
        directions=tuple(raw["directions"]),
        evidence=dict(raw["evidence"]),
        handled=raw["handled"],
        responses={int(k): v for k, v in raw.get("responses", {}).items()},
        named_by=tuple(raw.get("named_by", ())),
        logged_by=tuple(raw.get("logged_by", ())),
    )


class Registry:
    def __init__(self, payload: Mapping, *, source: str = "") -> None:
        self.source = source
        self.logs = tuple(payload["logs"])
        self.game: dict[tuple[int, int], OpcodeRecord] = {
            (int(k.split(",")[0]), int(k.split(",")[1])): _record(v)
            for k, v in payload["game"].items()
        }
        self.channel: dict[int, OpcodeRecord] = {
            int(k, 16): _record(v) for k, v in payload["channel"].items()
        }
        self.tagged_tags = tuple(payload["tagged_tags"])
        self.uncorroborated_tags = tuple(payload["uncorroborated_tags"])

    def __len__(self) -> int:
        return len(self.game)

    def lookup(self, main: int, sub: int) -> OpcodeRecord | None:
        """Game namespace only -- see `channel_lookup`."""
        return self.game.get((main, sub))

    def name_of(self, main: int, sub: int) -> str | None:
        rec = self.game.get((main, sub))
        return rec.name if rec else None

    def channel_lookup(self, raw: int) -> OpcodeRecord | None:
        """`raw` is the channel opcode as u16be, e.g. 0x7c03."""
        return self.channel.get(raw)

    def unhandled(self) -> tuple[OpcodeRecord, ...]:
        """Received with no handler, busiest first -- the work queue."""
        recs = [r for r in self.game.values() if r.handled is False]
        return tuple(sorted(recs, key=lambda r: (-r.hits, r.key)))

    def census(self) -> Census:
        by_direction = Counter()
        by_evidence = Counter()
        for rec in self.game.values():
            for d in rec.directions:
                by_direction[d] += 1
            for src in rec.evidence:
                by_evidence[src] += 1
        for rec in self.channel.values():
            by_evidence["channel"] += 1
        return Census(
            game=len(self.game),
            channel=len(self.channel),
            by_direction=dict(sorted(by_direction.items())),
            by_evidence=dict(sorted(by_evidence.items())),
            named=sum(1 for r in self.game.values() if r.name),
            dispatched=sum(1 for r in self.game.values() if r.handled is True),
            unhandled=sum(1 for r in self.game.values() if r.handled is False),
            unknown=sum(1 for r in self.game.values() if r.handled is None),
            uncorroborated_tags=self.uncorroborated_tags,
        )


def load(path: str | Path | None = None) -> Registry:
    p = Path(path) if path is not None else paths.OPCODES_JSON
    return Registry(json.loads(p.read_text(encoding="utf-8")), source=str(p))


@functools.lru_cache(maxsize=1)
def default_registry() -> Registry:
    return load()


def lookup(main: int, sub: int) -> OpcodeRecord | None:
    return default_registry().lookup(main, sub)


def name_of(main: int, sub: int) -> str | None:
    return default_registry().name_of(main, sub)


def channel_lookup(raw: int) -> OpcodeRecord | None:
    return default_registry().channel_lookup(raw)


def unhandled() -> tuple[OpcodeRecord, ...]:
    return default_registry().unhandled()


def census() -> Census:
    return default_registry().census()
