#!/usr/bin/env python3
"""Generate `src/uslocalserver/game/data/` from the 69 content tables.

The plan for M0 called for a dataclass per record set.  Measuring the bodies
before writing the generator changed two of its premises:

  * the record-set gate it proposed -- "key sets agree by Jaccard >= 0.9" --
    would have dropped `map_content.maps` (0.33) and `dungeon_content.dungeons`
    (0.40), i.e. two of the largest tables, because their records carry
    optional fields.  The gate here is instead *size and shape*: a `list` of
    `dict`s, or a `dict` of `dict`s, with at least `MIN_RECORDS` entries.
  * record sets are not only `list[dict]`.  `quest_content.quests` (3217),
    `creature_content.creatures` (3007) and `package_content.packages` (54030)
    are id-keyed `dict[str, dict]`.  Both shapes are handled.

`_index.json` is not consulted for any of this: its `kind` and its `top_keys`
are a digest of the body truncated to 12 keys, so they are wrong about exactly
the tables that carry the most fields.  Classification reads the body.

What gets generated:

    record set   @dataclass Row + `Record.load`
    config       no class; the top-level keys go into `CONFIG_KEYS`
    flat array   no class; `tuple[int, ...]` via `flat()`
    other        skipped, with the reason, into `_gen_models_skipped.json`

The type of a field is the union over *every* record in the set, never the
first one: inferring from `maps[0]` alone would type `map_content`'s optional
fields as required.  A key seen in fewer than two records is `Any`, and every
`Any` line is marked `# NEEDS-REVIEW` so the places with no real evidence
stay greppable.

Usage:
    python tools/gen_models.py [--check | --survey] [--out DIR]
"""
from __future__ import annotations

import argparse
import functools
import json
import keyword
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import map_tables                                            # noqa: E402
from uslocalserver import paths                              # noqa: E402

#: Below this a container is not treated as a record set.  The tables that sit
#: just under it (`cargo.personalTools` 16, `teleport_potions.towns` 16,
#: `hell_party.worldmaps` 15, `tournaments.tournaments` 2) are hand-written
#: config, and the test pins them as such: they are the cases where the
#: threshold, not the shape, decides.
MIN_RECORDS = 20

#: How deep to follow a value before giving up and saying `Any`.  Two levels
#: reach `drops: tuple[dict[str, int], ...]`; a third adds nothing but noise.
MAX_DEPTH = 3

BANNER = "# Generated by tools/gen_models.py -- do not edit, re-run the tool."

_SCALARS = {"int": "int", "bool": "bool", "str": "str", "float": "float"}
_ORDER = ("int", "float", "bool", "str")


def _union(kinds: set[str]) -> tuple[str, str | None]:
    """One annotation covering several scalar kinds, and why if it stayed a union.

    `bool` folds into `int` (`bool` *is* an `int` in Python) and `int` into
    `float`, so `{"bool", "int"}` is `int` and needs no review.  A genuine
    `int | str` does not fold, and the marker is what sends a reader to look
    at whether the field really has two shapes.
    """
    kinds = set(kinds)
    if "float" in kinds:
        kinds -= {"int", "bool"}
    elif "int" in kinds:
        kinds.discard("bool")
    if len(kinds) == 1:
        return _SCALARS[next(iter(kinds))], None
    names = " | ".join(k for k in _ORDER if k in kinds)
    return names, f"union of {names}"


class Skip(Exception):
    """A record set or table that cannot be modelled, with the reason why."""


def kind_of(value: Any) -> str:
    if value is None:
        return "none"
    if isinstance(value, bool):        # before int: bool is an int subclass
        return "bool"
    if isinstance(value, int):
        return "int"
    if isinstance(value, float):
        return "float"
    if isinstance(value, str):
        return "str"
    if isinstance(value, list):
        return "list"
    if isinstance(value, dict):
        return "dict"
    return "other"


def annotation(values: list, depth: int = 0) -> tuple[str, str | None]:
    """The narrowest annotation covering `values`, and why not if it is `Any`."""
    kinds = {kind_of(v) for v in values}
    optional = "none" in kinds
    kinds.discard("none")

    if not kinds:
        return "Any", "no value observed"
    if kinds <= set(_SCALARS):
        base, why = _union(kinds)
    elif len(kinds) > 1:
        return "Any", "mixed " + "|".join(sorted(kinds))
    else:
        only = kinds.pop()
        if depth >= MAX_DEPTH:
            base = "tuple[Any, ...]" if only == "list" else "dict[str, Any]"
            why = f"nested deeper than {MAX_DEPTH} levels"
        elif only == "list":
            base, why = _sequence([e for v in values for e in v], depth + 1)
        elif only == "dict":
            base, why = _mapping([x for v in values for x in v.values()], depth + 1)
        else:
            base, why = "Any", f"unsupported {only}"

    if optional and base != "Any" and not base.endswith("| None"):
        base = f"{base} | None"
    return base, why


def _sequence(values: list, depth: int) -> tuple[str, str | None]:
    if not values:
        return "tuple[Any, ...]", "empty in every record"
    inner, why = annotation(values, depth)
    if inner == "Any":
        return "tuple[Any, ...]", why
    return f"tuple[{inner}, ...]", f"elements {why}" if why else None


def _mapping(values: list, depth: int) -> tuple[str, str | None]:
    if not values:
        return "dict[str, Any]", "empty in every record"
    inner, why = annotation(values, depth)
    if inner == "Any":
        return "dict[str, Any]", why
    return f"dict[str, {inner}]", f"values {why}" if why else None


def field_defs(elements: list[dict]) -> list[tuple[str, str, str | None]]:
    """`(name, annotation, review reason)` per key, in first-appearance order.

    The order is the one the table body itself uses, which is stable because
    the body is a fixed file -- and it reads better than alphabetical, since
    `id` stays first.
    """
    seen: dict[str, list] = {}
    for element in elements:
        for name, value in element.items():
            if name not in seen:
                if not name.isidentifier() or keyword.iskeyword(name):
                    raise Skip(f"field name {name!r} is not usable as an attribute")
                seen[name] = []
            seen[name].append(value)

    total = len(elements)
    out = []
    for name, values in seen.items():
        if len(values) < 2:
            out.append((name, "Any", f"seen in {len(values)}/{total} records"))
            continue
        ann, why = annotation(values)
        if len(values) < total and ann != "Any" and not ann.endswith("| None"):
            ann = f"{ann} | None"
        out.append((name, ann, why))
    return out


def record_sets(body: Any) -> list[tuple[str | None, str, list[dict]]]:
    """`(container key, kind, records)` for every record set in `body`.

    The key is None when the body itself is the container.  The kind is
    `list` or `mapping`, and is kept only to know how to unwrap it again.
    """
    def candidate(key, value):
        if isinstance(value, list) and len(value) >= MIN_RECORDS:
            if not all(isinstance(e, dict) for e in value):
                return None
            return key, "list", value
        if isinstance(value, dict) and len(value) >= MIN_RECORDS:
            if not all(isinstance(e, dict) for e in value.values()):
                return None
            return key, "mapping", list(value.values())
        return None

    found = []
    if isinstance(body, dict):
        for key, value in body.items():
            got = candidate(key, value)
            if got and any(got[2]):
                found.append(got)
    else:
        got = candidate(None, body)
        if got and any(got[2]):
            found.append(got)
    return found


def classify(body: Any) -> str:
    if isinstance(body, dict):
        return "dict-with-records" if record_sets(body) else "config"
    if isinstance(body, list):
        if record_sets(body):
            return "record-set-root"
        if body and all(isinstance(e, int) and not isinstance(e, bool) for e in body):
            return "flat-list"
        return "unclassifiable"
    return "unclassifiable"


def flatten(body: Any) -> str:
    """`flat()`'s element type, for a body `classify` called `flat-list`."""
    ann, why = annotation(list(body))
    if ann != "int":
        raise Skip(f"flat array is {ann}, not int" + (f" ({why})" if why else ""))
    return "int"


def camel(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.split("_") if part)


def row_class(table: str, key: str | None) -> str:
    return f"{camel(table)}{camel(key) if key else ''}Row"


def survey(tables: dict[str, dict]) -> dict:
    """Everything the renderer needs, plus the reasons some of it is missing."""
    kinds: Counter = Counter()
    sets: list[dict] = []
    skipped: list[dict] = []
    flat: dict[str, str] = {}
    configs: dict[str, tuple[str, ...]] = {}
    containers: defaultdict[str, set] = defaultdict(set)

    for name in sorted(tables):
        body = tables[name]
        kind = classify(body)
        kinds[kind] += 1

        if kind == "unclassifiable":
            skipped.append({"name": name, "reason": f"root is {type(body).__name__}, not a record set"})
            continue

        if kind == "flat-list":
            try:
                flat[name] = flatten(body)
            except Skip as e:
                skipped.append({"name": name, "reason": str(e)})
                kinds[kind] -= 1
                kinds["unclassifiable"] += 1
            continue

        for key, shape, records in record_sets(body):
            where = key or "<root>"
            try:
                fields = field_defs(records)
            except Skip as e:
                skipped.append({"name": name, "reason": f"{where}: {e}"})
                continue
            if not fields:
                skipped.append({"name": name, "reason": f"{where}: every record is empty"})
                continue
            containers[name].add(key)
            sets.append({
                "table": name,
                "key": key,
                "shape": shape,
                "records": len(records),
                "fields": fields,
                "class": row_class(name, key),
            })

    # Every table, modelled or not: `load` reaches all 69 by canonical name.
    for name in sorted(tables):
        body = tables[name]
        if isinstance(body, dict):
            configs[name] = tuple(k for k in body if k not in containers[name])
        else:
            configs[name] = ()

    return {
        "kinds": dict(sorted(kinds.items())),
        "configs": configs,
        "flat": flat,
        "record_sets": sets,
        "skipped": sorted(skipped, key=lambda s: (s["name"], s["reason"])),
    }


def _reviewed(field: tuple) -> bool:
    return field[2] is not None


def render_models(surveyed: dict) -> str:
    sets = surveyed["record_sets"]
    fields = [f for s in sets for f in s["fields"]]
    any_fields = sum(1 for f in fields if "Any" in f[1])
    marked = sum(1 for f in fields if _reviewed(f))

    out = [
        BANNER,
        f'"""Typed rows for the {len(sets)} record sets among the 69 content tables.',
        "",
        "A field's type is the union over every record in its set, never the first",
        "record.  Two things stop the union from narrowing to a single type and get",
        "a `# NEEDS-REVIEW` marker instead of a guess: `Any` (usually a key seen in",
        "fewer than two records) and a genuine union, so that the fields whose shape",
        "is unsettled stay greppable.  Fields absent from some records are optional,",
        "and `load` supplies None for them.",
        '"""',
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "from typing import Any, Mapping",
        "",
        "",
        "def _coerce(value: Any) -> Any:",
        "    \"\"\"JSON arrays are lists; the annotations say tuple.\"\"\"",
        "    if isinstance(value, list):",
        "        return tuple(_coerce(v) for v in value)",
        "    if isinstance(value, dict):",
        "        return {k: _coerce(v) for k, v in value.items()}",
        "    return value",
        "",
        "",
        "class Record:",
        "    \"\"\"Base of the generated rows; every subclass is frozen.",
        "",
        "    Not slotted on purpose: on 3.11 `slots=True` rewrites the class and",
        "    leaves the frozen guard raising TypeError instead of",
        "    FrozenInstanceError, which is a trap for anyone catching the latter.",
        "    \"\"\"",
        "",
        "    @classmethod",
        "    def load(cls, raw: Mapping[str, Any]):",
        "        \"\"\"One record; keys the class does not declare are dropped.\"\"\"",
        "        return cls(**{name: _coerce(raw.get(name))",
        "                      for name in cls.__dataclass_fields__})",
    ]

    for entry in sets:
        key = entry["key"]
        out += [
            "",
            "",
            f"# {entry['table']}.{key}" if key else f"# {entry['table']} (root)",
            f"# {entry['shape']} of {entry['records']} records",
            "@dataclass(frozen=True)",
            f"class {entry['class']}(Record):",
        ]
        for name, ann, why in entry["fields"]:
            line = f"    {name}: {ann}"
            if why:
                line += f"  # NEEDS-REVIEW: {why}"
            out.append(line)

    body = "\n".join(out) + "\n"
    return (f"{body}\n\n# {marked} of the {len(fields)} fields above carry NEEDS-REVIEW "
            f"({any_fields} of them Any).\n")


def render_package(surveyed: dict, docstring: str) -> str:
    sets = surveyed["record_sets"]
    classes = sorted({s["class"] for s in sets})

    out = [
        BANNER,
        f'"""{docstring}"""',
        "from __future__ import annotations",
        "",
        "import functools",
        "import json",
        "from typing import Any",
        "",
        "from uslocalserver import paths",
        "",
    ]
    if classes:
        out.append("from .models import (")
        out += [f"    {c}," for c in classes]
        out.append(")")
    out.append("")

    out += [
        "FILES: dict[str, str] = {",
    ]
    for name in sorted(surveyed["configs"]):
        out.append(f'    "{name}": "{surveyed["files"][name]}",')
    out.append("}")
    out += [
        '"""Canonical table name -> `data/tables/` file.  Neither the `NNN_`',
        "prefix nor the slug is an identity: nine documents share a slug with",
        'another document."""',
        "",
        "CONFIG_KEYS: dict[str, tuple[str, ...]] = {",
    ]
    for name, keys in sorted(surveyed["configs"].items()):
        if not keys:
            out.append(f'    "{name}": (),')
        else:
            out.append(f'    "{name}": (')
            out += [f'        "{k}",' for k in keys]
            out.append("    ),")
    out.append("}")
    out += [
        '"""Table name -> the top-level keys that are not record sets."""',
        "",
    ]

    if sets:
        grouped: dict[str, list[dict]] = {}
        for entry in sets:
            grouped.setdefault(entry["table"], []).append(entry)
        out.append("RECORD_SETS: dict[str, dict[str | None, type[Any]]] = {")
        for name, entries in sorted(grouped.items()):
            out.append(f'    "{name}": {{')
            for entry in entries:
                key = "None" if entry["key"] is None else f'"{entry["key"]}"'
                out.append(f"        {key}: {entry['class']},")
            out.append("    },")
        out.append("}")
        out += [
            '"""Table name -> {container key: row class}.  A table with more than',
            "one set -- `hell_party` has three, `teleport_potions` four -- needs the",
            'key; None is the key of a body that is the record set itself."""',
            "",
        ]

    if surveyed["flat"]:
        out.append("FLAT_ARRAYS: dict[str, str] = {")
        for name, elem in sorted(surveyed["flat"].items()):
            out.append(f'    "{name}": "{elem}",')
        out.append("}")
        out.append("")

    out += [
        "",
        "@functools.lru_cache(maxsize=None)",
        "def load(name: str) -> Any:",
        '    """The decoded body of `name`.  Shared: treat it as read-only."""',
        '    return json.loads((paths.TABLES_DIR / FILES[name]).read_text(encoding="utf-8"))',
    ]

    if sets:
        out += [
            "",
            "",
            "def rows(name: str, key: str | None = None) -> tuple[Any, ...]:",
            '    """The records of `name`; `key` is only needed when there are several."""',
            "    sets = RECORD_SETS[name]",
            "    if key is None:",
            "        if len(sets) > 1:",
            "            raise KeyError(f\"{name} holds {len(sets)} record sets, name one: \"",
            "                           f\"{sorted(k for k in sets if k is not None)}\")",
            "        key, cls = next(iter(sets.items()))",
            "    else:",
            "        cls = sets[key]",
            "    body = load(name)",
            "    raw = body if key is None else body[key]",
            "    if isinstance(raw, dict):",
            "        raw = list(raw.values())",
            "    return tuple(cls.load(r) for r in raw)",
        ]

    if surveyed["flat"]:
        ann = sorted(set(surveyed["flat"].values()))
        elem = ann[0] if len(ann) == 1 else "Any"
        out += [
            "",
            "",
            f"def flat(name: str) -> tuple[{elem}, ...]:",
            '    """A table whose body is a bare array of numbers."""',
            "    return tuple(load(name))",
        ]

    return "\n".join(out) + "\n"


def build() -> dict:
    by_name = map_tables.by_name()
    tables = {}
    files = {}
    for name, entry in sorted(by_name.items()):
        files[name] = entry["file"]
        tables[name] = json.loads(
            (paths.TABLES_DIR / entry["file"]).read_text(encoding="utf-8"))
    surveyed = survey(tables)
    surveyed["files"] = files
    return surveyed


def render(surveyed: dict) -> dict[str, str]:
    return {
        "models.py": render_models(surveyed),
        "__init__.py": render_package(
            surveyed,
            "Generated content-table models and loaders (see tools/gen_models.py).\n\n"
            "`load` is the raw JSON; `rows` is the typed view of the record sets;\n"
            "`CONFIG_KEYS` lists what is left over.  Table files are found by the\n"
            "canonical name from `_table_map.json`, never by number or slug."),
    }


def render_skipped(surveyed: dict) -> str:
    return json.dumps({
        "generated_by": "tools/gen_models.py",
        "min_records": MIN_RECORDS,
        "kinds": surveyed["kinds"],
        "skipped": surveyed["skipped"],
    }, indent=1, ensure_ascii=False) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=paths.GAME_DATA_DIR)
    ap.add_argument("--skipped", type=Path, default=paths.GEN_MODELS_SKIPPED)
    ap.add_argument("--check", action="store_true",
                    help="verify the committed output instead of rewriting it")
    ap.add_argument("--survey", action="store_true",
                    help="report the classification and write nothing")
    a = ap.parse_args()

    surveyed = build()
    rendered = render(surveyed)

    if a.survey:
        for kind, count in surveyed["kinds"].items():
            print(f"  {kind:20} {count}")
        print(f"  record sets          {len(surveyed['record_sets'])}")
        for e in surveyed["record_sets"]:
            print(f"    {e['table']}.{e['key'] or '<root>':12} {e['shape']:8} "
                  f"{e['records']:>6}  {len(e['fields']):>3} fields  {e['class']}")
        print(f"  flat arrays          {surveyed['flat']}")
        print(f"  skipped              {len(surveyed['skipped'])}")
        for s in surveyed["skipped"]:
            print(f"    {s['name']}: {s['reason']}")
        return 0

    skipped = render_skipped(surveyed)
    if a.check:
        stale = [n for n, text in rendered.items()
                 if (a.out / n).read_text(encoding="utf-8") != text]
        if skipped != a.skipped.read_text(encoding="utf-8"):
            stale.append(a.skipped.name)
        if stale:
            raise SystemExit(f"stale, re-run without --check: {', '.join(sorted(stale))}")
        print(f"{a.out} is current")
        return 0

    a.out.mkdir(parents=True, exist_ok=True)
    for name, text in rendered.items():
        (a.out / name).write_text(text, encoding="utf-8")
    a.skipped.write_text(skipped, encoding="utf-8")

    sets = surveyed["record_sets"]
    fields = [f for s in sets for f in s["fields"]]
    marked = sum(1 for f in fields if _reviewed(f))
    any_fields = sum(1 for f in fields if "Any" in f[1])
    print(f"wrote {a.out}")
    print(f"  kinds    {surveyed['kinds']}")
    print(f"  rows     {len(sets)} record sets, {len(fields)} fields, "
          f"{marked} need review ({any_fields} of them Any)")
    print(f"  config   {len(surveyed['configs'])} tables keyed, "
          f"flat {surveyed['flat'] or '{}'}")
    print(f"  skipped  {len(surveyed['skipped'])} -> {a.skipped}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
